name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - backend-dev  # 觸發部署的分支

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # 這裡會自動讀取 GCP_PROJECT_ID
  SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  REGION: ${{ secrets.GCP_REGION }}
  REPO: asia-east1-docker.pkg.dev  # Artifact Registry 的位置

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REPO

      - name: Build and Push Docker Image
        run: |
          docker build -t $REPO/$PROJECT_ID/in-out-system-docker-repo/$SERVICE:$GITHUB_SHA .
          docker push $REPO/$PROJECT_ID/in-out-system-docker-repo/$SERVICE:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REPO/$PROJECT_ID/in-out-system-docker-repo/$SERVICE:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated